### ISSUE TITLE
«Call to a member function getActionFlag() on null in app/code/Itoris/PendingRegistration/Helper/Data.php:407»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#22]
```
#0 app/code/Itoris/PendingRegistration/Helper/Data.php(121): Itoris\PendingRegistration\Helper\Data->safeExit(NULL)
#1 app/code/Itoris/PendingRegistration/Observers/Register/RegisterSuccess.php(111): Itoris\PendingRegistration\Helper\Data->customerLogout(NULL)
#2 vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Itoris\PendingRegistration\Observers\Register\RegisterSuccess->execute(Object(Magento\Framework\Event\Observer))
#3 vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Itoris\PendingRegistration\Observers\Register\RegisterSuccess), Object(Magento\Framework\Event\Observer))
#4 vendor/magento/framework/Event/Manager.php(66)
```

**Comment by dmitrii-fediuk** [comment]
Fixed by patching `app/code/Itoris/PendingRegistration/Helper/Data.php`
