### ISSUE TITLE
«Call to a member function getDescription() on null in vendor/pmclain/magento2-authorizenetcim/Gateway/Validator/ResponseValidator/Authorize.php:32»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#23]
```
#0 vendor/pmclain/magento2-authorizenetcim/Gateway/Validator/GeneralResponseValidator.php(44): Pmclain\AuthorizenetCim\Gateway\Validator\ResponseValidator\Authorize->Pmclain\AuthorizenetCim\Gateway\Validator\ResponseValidator\{closure}(Object(Magento\Framework\DataObject))
#1 vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(105): Pmclain\AuthorizenetCim\Gateway\Validator\GeneralResponseValidator->validate(Array)
#2 vendor/magento/module-payment/Model/Method/Adapter.php(546): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)
#3 vendor/magento/module-payment/Model/Method/Adapter.php(448): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
```

**Comment by dmitrii-fediuk** [comment]
Fixed by patching `vendor/pmclain/magento2-authorizenetcim/Gateway/Validator/ResponseValidator/Authorize.php`.
