### ISSUE TITLE
«Class 'Amasty\Checkout\Model\CouldNotSaveException' not found in app/code/Amasty/Checkout/Model/GuestPaymentInformationManagement.php:47»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#24]
```
#0 vendor/magento/framework/Interception/Interceptor.php(58): Amasty\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('03e3d8aaca80cbc...', 'lauriescandies@...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor), Array)
#1 vendor/magento/framework/Interception/Interceptor.php(138): Amasty\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(153): Amasty\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('03e3d8aaca80cbc...', 'lauriescandies@...', Object(Magento\Quote\Model\Quote\Payment\Interceptor),' in 'app/code/Amasty/Checkout/Model/GuestPaymentInformationManagement.php' on line 47"
```

**Comment by dmitrii-fediuk** [comment]
Fixed by patching `app/code/Amasty/Checkout/Model/GuestPaymentInformationManagement.php`.
