### ISSUE TITLE
«Call to a member function getLayout() on null in app/code/Rokanthemes/LayeredAjax/Plugins/Controller/Category/View.php:20»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#25]
```
#0 vendor/magento/framework/Interception/Interceptor.php(146): Rokanthemes\LayeredAjax\Plugins\Controller\Category\View->afterExecute(Object(MGS\Mpanel\Controller\Category\View\Interceptor), NULL)
#1 vendor/magento/framework/Interception/Interceptor.php(153): MGS\Mpanel\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#2 generated/code/MGS/Mpanel/Controller/Category/View/Interceptor.php(26): MGS\Mpanel\Controller\Category\View\Interceptor->___callPlugins('execute', Array, Array)
#3 vendor/magento/framework/App/Action/Action.php(107): MGS\Mpanel\Controller\Category\View\Interceptor->execute()
#4 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action-
```

**Comment by dmitrii-fediuk** [comment]
Fixed by patching the `app/code/Rokanthemes/LayeredAjax/Plugins/Controller/Category/View.php` file.
