### ISSUE TITLE
«Cannot instantiate abstract class Akeans\Pocustomize\Controller\Adminhtml\Invoice\Paid»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#38]
```
Stack trace:
#0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Akeans\\Pocustom...', Array)
#1 vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Akeans\\Pocustom...', Array)
#2 vendor/magento/framework/App/ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Akeans\\Pocustom...')
#3 vendor/magento/framework/App/Router/Base.php(297): Magento\Framework\App\ActionFactory->create('Akeans\\Pocustom...')
#4 vendor/magento/framework/App/Router/Base.php(158): Magento\Framework\App\Router\Base->matchAction(Object(Magento\ 
```

**Comment by dmitrii-fediuk** [comment]
Fixed in `app/code/Akeans/Pocustomize/Controller/Adminhtml/Invoice/Paid.php`.
