### ISSUE TITLE
«Call to undefined method Mirasvit\SearchReport\Service\LogService::getId() in app/code/Mirasvit/SearchReport/Plugin/ResponsePlugin.php:92»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#39]
```
Stack trace:
#0 vendor/magento/framework/Interception/Interceptor.php(121): Mirasvit\SearchReport\Plugin\ResponsePlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#1 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}()
#2 generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#3 vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#4 pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\
Файл: app/code/Mirasvit/SearchReport/Plugin/ResponsePlugin.php
```

**Comment by dmitrii-fediuk** [comment]
Fixed in `app/code/Mirasvit/SearchReport/Plugin/ResponsePlugin.php`.
