### ISSUE TITLE
«Cannot instantiate abstract class Magento\Customer\Controller\Adminhtml\Index»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#40]
```
#0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Custome...', Array)
#1 vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Custome...', Array)
#2 vendor/magento/framework/App/ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Custome...')
#3 vendor/magento/framework/App/Router/Base.php(297): Magento\Framework\App\ActionFactory->create('Magento\\Custome...')
#4 vendor/magento/framework/App/Router/Base.php(158): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework
```

**Comment by dmitrii-fediuk** [comment]
The issue last occured at 2019-11-12.
