### ISSUE TITLE
«Call to a member function getStoreId() on null in vendor/magento/module-quote/Model/Quote/Payment.php:286»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#43]
```
#0 vendor/magento/module-quote/Model/Quote/Payment.php(180): Magento\Quote\Model\Quote\Payment->getMethodInstance()
#1 vendor/magento/module-sales/Model/AdminOrder/Create.php(1572): Magento\Quote\Model\Quote\Payment->importData(Object(Magento\Framework\DataObject))
#2 vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Save.php(42): Magento\Sales\Model\AdminOrder\Create->setPaymentData(Array)
#3 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Create\Save->execute()
#4 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent('execute', Array)
#5 vendor/magento/framework/
```

**Comment by dmitrii-fediuk** [comment]
I am unable to reproduce it via a backend order.
