### ISSUE TITLE
`Webkul_AmazonMagentoConnect`: «A field name was provided without a field value in vendor/zendframework/zend-http/src/Headers.php:192»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#45]
```
#0 vendor/zendframework/zend-http/src/Headers.php(155): Zend\Http\Headers->addHeaderLine('Mozilla/5.0 (Wi...')
#1 vendor/zendframework/zend-http/src/PhpEnvironment/Request.php(236): Zend\Http\Headers->addHeaders(Array)
#2 vendor/zendframework/zend-http/src/PhpEnvironment/Request.php(84): Zend\Http\PhpEnvironment\Request->setServer(Object(Zend\Stdlib\Parameters))
#3 vendor/magento/framework/HTTP/PhpEnvironment/Request.php(133): Zend\Http\PhpEnvironment\Request->__construct()
#4 vendor/magento/framework/App/Request/Http.php(115): Magento\Framework\HTTP\PhpEnvironment\Request->__construct(Object(Magento\Framework\Stdlib\Cookie\PhpCookieReader), Object(Magento\Framework\Stdlib\StringUtils), NULL)
```

**Comment by dmitrii-fediuk** [comment]
The isssue is caused by the `\Webkul\AmazonMagentoConnect\Helper\Product::saveImage()` method.

**Comment by dmitrii-fediuk** [comment]
I have implemented a loggin in the `vendor/zendframework/zend-http/src/Headers.php` file.
