### ISSUE TITLE
«This email address is already subscribed»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [royalwholesalecandy/core#58]
```
#0 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#1 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('execute', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(26): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('execute', Array, Array)
#4 vendor/magento/framework/App/Action/Action.php(107): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute()
#5 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#7 app/code/Bss/Paymentshipping/Plugin/App/Action/Context.php(81): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#8 vendor/magento/framework/Interception/Interceptor.php(135): Bss\Paymentshipping\Plugin\App\Action\Context->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(39): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, NULL)
#11 vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#13 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#14 vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 app/code/TemplateMonster/SiteMaintenance/Model/PageCache/App/FrontController/BuiltinPlugin.php(30): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 vendor/magento/framework/Interception/Interceptor.php(135): TemplateMonster\SiteMaintenance\Model\PageCache\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#23 vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#24 pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
```

**Comment by dmitrii-fediuk** [comment]
I have implemented a logging in `\Magento\Newsletter\Controller\Subscriber\NewAction::execute()`.

**Comment by dmitrii-fediuk** [comment]
```
This email address is already subscribed: domdonovan@gmail.com
Array
(
    [0] => Array
        (
            [File] => vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php
            [Line] => 136
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction::execute
            [Callee] => df_log_l
        )

    [1] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 58
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callParent
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction::execute
        )

    [2] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 138
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callParent
        )

    [3] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 153
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callPlugins
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
        )

    [4] => Array
        (
            [File] => generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php
            [Line] => 26
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::execute
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callPlugins
        )

    [5] => Array
        (
            [File] => vendor/magento/framework/App/Action/Action.php
            [Line] => 107
            [Caller] => Magento\Framework\App\Action\Action::dispatch
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::execute
        )

    [6] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 58
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callParent
            [Callee] => Magento\Framework\App\Action\Action::dispatch
        )

    [7] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 138
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callParent
        )

    [8] => Array
        (
            [File] => app/code/Bss/Paymentshipping/Plugin/App/Action/Context.php
            [Line] => 81
            [Caller] => Bss\Paymentshipping\Plugin\App\Action\Context::aroundDispatch
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
        )

    [9] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 135
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => Bss\Paymentshipping\Plugin\App\Action\Context::aroundDispatch
        )

    [10] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 153
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callPlugins
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::Magento\Framework\Interception\{closure}
        )

    [11] => Array
        (
            [File] => generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php
            [Line] => 39
            [Caller] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::dispatch
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::___callPlugins
        )

    [12] => Array
        (
            [File] => vendor/magento/framework/App/FrontController.php
            [Line] => 55
            [Caller] => Magento\Framework\App\FrontController::dispatch
            [Callee] => Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor::dispatch
        )

    [13] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 58
            [Caller] => Magento\Framework\App\FrontController\Interceptor::___callParent
            [Callee] => Magento\Framework\App\FrontController::dispatch
        )

    [14] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 138
            [Caller] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => Magento\Framework\App\FrontController\Interceptor::___callParent
        )

    [15] => Array
        (
            [File] => vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php
            [Line] => 94
            [Caller] => Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch
            [Callee] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
        )

    [16] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 135
            [Caller] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch
        )

    [17] => Array
        (
            [File] => vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php
            [Line] => 73
            [Caller] => Magento\PageCache\Model\App\FrontController\BuiltinPlugin::aroundDispatch
            [Callee] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
        )

    [18] => Array
        (
            [File] => app/code/TemplateMonster/SiteMaintenance/Model/PageCache/App/FrontController/BuiltinPlugin.php
            [Line] => 30
            [Caller] => TemplateMonster\SiteMaintenance\Model\PageCache\App\FrontController\BuiltinPlugin::aroundDispatch
            [Callee] => Magento\PageCache\Model\App\FrontController\BuiltinPlugin::aroundDispatch
        )

    [19] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 135
            [Caller] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
            [Callee] => TemplateMonster\SiteMaintenance\Model\PageCache\App\FrontController\BuiltinPlugin::aroundDispatch
        )

    [20] => Array
        (
            [File] => vendor/magento/framework/Interception/Interceptor.php
            [Line] => 153
            [Caller] => Magento\Framework\App\FrontController\Interceptor::___callPlugins
            [Callee] => Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure}
        )

    [21] => Array
        (
            [File] => generated/code/Magento/Framework/App/FrontController/Interceptor.php
            [Line] => 26
            [Caller] => Magento\Framework\App\FrontController\Interceptor::dispatch
            [Callee] => Magento\Framework\App\FrontController\Interceptor::___callPlugins
        )

    [22] => Array
        (
            [File] => vendor/magento/framework/App/Http.php
            [Line] => 135
            [Caller] => Magento\Framework\App\Http::launch
            [Callee] => Magento\Framework\App\FrontController\Interceptor::dispatch
        )

    [23] => Array
        (
            [File] => generated/code/Magento/Framework/App/Http/Interceptor.php
            [Line] => 24
            [Caller] => Magento\Framework\App\Http\Interceptor::launch
            [Callee] => Magento\Framework\App\Http::launch
        )

    [24] => Array
        (
            [File] => vendor/magento/framework/App/Bootstrap.php
            [Line] => 256
            [Caller] => Magento\Framework\App\Bootstrap::run
            [Callee] => Magento\Framework\App\Http\Interceptor::launch
        )

    [25] => Array
        (
            [File] => pub/index.php
            [Line] => 37
            [Caller] => 
            [Callee] => Magento\Framework\App\Bootstrap::run
        )

)
```

**Comment by dmitrii-fediuk** [comment]
I have enchanced logging in `\Magento\Newsletter\Controller\Subscriber\NewAction::execute()`.

**Comment by dmitrii-fediuk** [comment]
I have enchanced logging in \Magento\Newsletter\Controller\Subscriber\NewAction::execute() again.
